server:
  port: 8080

job:
  notification:
    delay: 10000

telegram:
  api-url: https://api.telegram.org/bot
  token:

version: 1.0

external:
  url:


spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username:
    password:
