server:
  port: 8080

logging:
  path: /var/log/library/

job:
  notification:
    delay: 10000

telegram:
  api-url: https://api.telegram.org/bot

version:
  1.0

external:
  url:

  #spring:
  # datasource:
  #  hikari:
  #   connection-timeout: 20000
#  maximum-pool-size: 5